### ISSUE TITLE
Remote Control Effects

### ISSUE THREAD

**Issue by FxSchrauber** [fx-planet/fxplanet#1]
Hello,

When it was still about the presentation in the forum, there was the following idea regarding "Remote Control Effects":

> schrauber wrote:
> Control Effects: I think the handling is too complicated in practice. 
> Also some effects contain filter settings with unclear compatibility....

>jwrl wrote: 
>  I have a plan B: what about having a separate thread, with a link to it from the effects by category?

> schrauber wrote: That would be perfect.

**Issue 1:**
RC1_Remote_control.fx (maybe it also affects other effects?)?
`MagFilter = PYRAMIDALQUAD;`
Unclear compatibility (Is different from the  Cg 3.1 Reference Manual) 
It works with Windows, Intel HD Graphics 4600
Alternative codes known to me have other disadvantages, or are also controversial.

**Issue 2:** Various effects
`AddressU = Clamp;   AddressV = Clamp;`
Possible solutions are known.

**Issue 3:** Various effects
Incompatible with Lightworks 14.5 GPU Precision Settings "**16-bit Floating Point**".
Suspected cause: Rounding error of the remote controller status value.
Solution: Change Code (use a tolerance range when checking the status value.)

Do we want to hide, remove, or move these effects to a submenu less visible? Maybe with compatibility warnings mark?

**Comment by marcinn** [comment]
This issue was moved to fx-planet/lwks-fx-bundle#2
